import { codeUnitCompare } from "./strict-json-v1.js";

/**
 * The one text collation Catalog production uses where an English order is observable in
 * generated bytes or digests. It reproduces the order Core's generators produced under an
 * English process locale, but never reads the process default locale: the locale and every
 * collation option are pinned here.
 */
const CATALOG_COLLATOR_V1 = new Intl.Collator("en", {
  usage: "sort",
  sensitivity: "variant",
  ignorePunctuation: false,
  numeric: false,
  caseFirst: "false",
  collation: "default",
});

/** Fixed vectors whose English order the committed defaults depend on. */
const CANARY_V1 = ["a", "a-b", "a/b", "alpha", "code-review", "codebase-design", "Zeta"];

function assertPinnedCollatorV1(): void {
  const resolved = CATALOG_COLLATOR_V1.resolvedOptions();
  if (resolved.locale !== "en" || resolved.collation !== "default") {
    throw new Error(
      `Catalog collation requires ICU English collation; this runtime resolved ${resolved.locale}/${resolved.collation}`,
    );
  }
  const sorted = [...CANARY_V1].reverse().sort(CATALOG_COLLATOR_V1.compare);
  if (sorted.join("\n") !== CANARY_V1.join("\n")) {
    throw new Error(
      "Catalog collation: this runtime's English collation does not match the pinned order",
    );
  }
}

assertPinnedCollatorV1();

/** Total order: English collation, with code-unit order breaking collation ties. */
export function catalogTextCompareV1(left: string, right: string): number {
  return CATALOG_COLLATOR_V1.compare(left, right) || codeUnitCompare(left, right);
}

/**
 * The runtime versions that decide Catalog text order: the ICU library, and the Unicode and
 * CLDR data it collates with, as shipped by this Node. Production records them so a
 * regeneration difference on another machine can be traced to a different collation runtime.
 */
export interface CatalogProductionRuntimeV1 {
  node: string;
  icu: string;
  unicode: string;
  cldr: string;
}

export function catalogProductionRuntimeV1(): CatalogProductionRuntimeV1 {
  const { node, icu, unicode, cldr } = process.versions;
  if (icu === undefined || unicode === undefined || cldr === undefined)
    throw new Error("Catalog production requires a Node built with full ICU");
  return { node, icu, unicode, cldr };
}
