import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const root = resolve(import.meta.dirname, "..", "..");

describe("committed Catalog defaults check", () => {
  it("refuses one stale committed default even when the working file has regenerated bytes", async () => {
    const { checkCommittedCatalogDefaults } = await import(
      // @ts-expect-error The committed-byte check is an ESM maintenance tool.
      "../../tools/check-committed-catalog-defaults.mjs"
    );
    const generated = new Map<string, Buffer>();
    const { buildCatalogFrameworkDefaultsV1, serializeCatalogDefaultV1 } = await import(
      "../../src/production/catalog-defaults-v1.js"
    );
    for (const [path, value] of Object.entries(buildCatalogFrameworkDefaultsV1(root))) {
      generated.set(path, Buffer.from(serializeCatalogDefaultV1(value)));
    }
    const stale = "defaults/catalog-scanner-providers-v1.json";
    const current = generated.get(stale);
    if (!current) throw new Error("missing generated default");
    expect(() =>
      checkCommittedCatalogDefaults(root, (_root: string, path: string) =>
        path === stale ? Buffer.concat([current, Buffer.from(" ")]) : generated.get(path),
      ),
    ).toThrow(`${stale} is stale in HEAD`);
    expect(readFileSync(resolve(root, stale))).toEqual(current);
  }, 20_000);
});
